In [ ]:
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline
# import os
# os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";
# os.environ["CUDA_VISIBLE_DEVICES"]="0";   
# import tensorflow as tf
# tf.config.list_physical_devices('GPU')

In [1]:
pip install datasets

     |████████████████████████████████| 298 kB 5.1 MB/s 
     |████████████████████████████████| 1.1 MB 30.1 MB/s 
     |████████████████████████████████| 132 kB 41.2 MB/s 
     |████████████████████████████████| 243 kB 39.3 MB/s 
     |████████████████████████████████| 61 kB 505 kB/s 
     |████████████████████████████████| 160 kB 42.3 MB/s 
     |████████████████████████████████| 271 kB 48.6 MB/s 
     |████████████████████████████████| 192 kB 47.7 MB/s 


In [2]:
pip install transformers

     |████████████████████████████████| 3.3 MB 5.5 MB/s 
     |████████████████████████████████| 596 kB 46.1 MB/s 
     |████████████████████████████████| 3.3 MB 45.8 MB/s 
     |████████████████████████████████| 895 kB 29.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
pip install fasttext

     |████████████████████████████████| 68 kB 3.4 MB/s 
  Using cached pybind11-2.8.1-py2.py3-none-any.whl (208 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp37-cp37m-linux_x86_64.whl size=3126866 sha256=06eb38185209da98de99d529fdf24e28a8b7f8385a5e6d18f93d97747e5d22bd
  Stored in directory: /root/.cache/pip/wheels/4e/ca/bf/b020d2be95f7641801a6597a29c8f4f19e38f9c02a345bab9b
Successfully built fasttext


In [4]:
pip install ktrain

     |████████████████████████████████| 25.3 MB 46.9 MB/s 
     |████████████████████████████████| 6.8 MB 36.6 MB/s 
     |████████████████████████████████| 981 kB 47.8 MB/s 
     |████████████████████████████████| 263 kB 48.5 MB/s 
     |████████████████████████████████| 2.8 MB 34.5 MB/s 
     |████████████████████████████████| 1.2 MB 37.4 MB/s 
     |████████████████████████████████| 468 kB 44.9 MB/s 
  Created wheel for ktrain: filename=ktrain-0.28.3-py3-none-any.whl size=25292659 sha256=610dba7253012642957df72c47fc6433b5580579f95638774645076aa6a9f526
  Stored in directory: /root/.cache/pip/wheels/6a/7e/c3/f46cdfc2b81c54424923b1405d7e670c35cacc11ada9a47b1c
  Created wheel for seqeval: filename=seqeval-0.0.19-py3-none-any.whl size=9929 sha256=b8a6c6bd55cec9ee28aaa84dc359d4d5c69db25b86c364cf496306151b0bb017
  Stored in directory: /root/.cache/pip/wheels/f5/ac/f1/4e13d7aff05c722d142b7d20a88ad63f9aab11b895411241a4
  Created wheel for keras-bert: filename=keras_bert-0.88.0-py3-none-any.w

In [5]:
pip install imbalanced-learn

     |████████████████████████████████| 23.2 MB 21.4 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ktrain 0.28.3 requires scikit-learn==0.23.2, but you have scikit-learn 1.0.1 which is incompatible.


In [6]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from datasets import load_dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn import metrics
from collections import Counter
import transformers
import numpy as np
import fasttext
import ktrain
from ktrain import text
from imblearn.over_sampling import RandomOverSampler

# 1. Get acquainted with the data of the Polish Cyberbullying detection dataset. Pay special attention to the distribution of the positive and negative examples in the first task as well as distribution of the classes in the second task.

In [7]:
def get_results(y_test, y_pred):
    print("Confusion matrix: ")
    print(metrics.confusion_matrix(y_test, y_pred))
    # sklearn.metrics.ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
    # plt.show()
    print("Classification: ")
    print(metrics.classification_report(y_test, y_pred))
    print("MCC: ")
    print(metrics.matthews_corrcoef(y_test, y_pred))

# 2. Train the following classifiers on the training sets (for the task 1 and the task 2):

- Bayesian classifier with TF * IDF weighting.
- Fasttext text classifier
- Transformer classifier (take into account that a number of experiments should be performed for this model).


# Task01

In [ ]:
dataset = load_dataset("poleval2019_cyberbullying", "task01")

Reusing dataset poleval2019_cyber_bullying (/root/.cache/huggingface/datasets/poleval2019_cyber_bullying/task01/1.0.0/ce6060c56dae43c469bab309a7573b86299b0bcc2484e85cfe0ae70b5f770450)


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
x_train = dataset["train"]['text']
x_test = dataset["test"]['text']

vectorizer = TfidfVectorizer()
train_vector = vectorizer.fit_transform(x_train).toarray()
test_vector = vectorizer.transform(x_test).toarray()

gnb = GaussianNB()
mnb = MultinomialNB()

y_pred = gnb.fit(train_vector, dataset["train"]["label"]).predict(test_vector)
print("GaussianNB")
get_results(dataset["test"]["label"], y_pred)

y_pred = mnb.fit(train_vector, dataset["train"]["label"]).predict(test_vector) # raczej multinomial jest uzywany do tekstu
print("MultinomialNB")
get_results(dataset["test"]["label"], y_pred)


GaussianNB
Confusion matrix: 
[[742 124]
 [ 94  40]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.86      0.87       866
           1       0.24      0.30      0.27       134

    accuracy                           0.78      1000
   macro avg       0.57      0.58      0.57      1000
weighted avg       0.80      0.78      0.79      1000

MCC: 
0.1428942557422714
MultinomialNB
Confusion matrix: 
[[866   0]
 [133   1]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       1.00      0.01      0.01       134

    accuracy                           0.87      1000
   macro avg       0.93      0.50      0.47      1000
weighted avg       0.88      0.87      0.81      1000

MCC: 
0.08043106192813237


In [ ]:
print(Counter(dataset["train"]["label"]))
# set jest niezbalansowany

Counter({0: 9190, 1: 851})


In [ ]:
# Przygotowanie pliku pod fasttext
x_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]

with open("train_data.txt", 'wb') as f:
    f.writelines([f"__label__{label} {sentence}\n".encode() for sentence, label in zip(x_train, y_train)])

In [ ]:
model = fasttext.train_supervised("train_data.txt")

y_pred, _ = model.predict(x_test)
y_pred = [int(label[0].split("__label__")[1]) for label in y_pred]
y_test = dataset["test"]["label"]
get_results(dataset["test"]["label"], y_pred)

Confusion matrix: 
[[851  15]
 [112  22]]
Classification: 
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       866
           1       0.59      0.16      0.26       134

    accuracy                           0.87      1000
   macro avg       0.74      0.57      0.59      1000
weighted avg       0.84      0.87      0.84      1000

MCC: 
0.2650301059500807


dodać zmienianie do małych liter, dodać ujednolicenie ilosci, dodac inne parametry do transformerów przy uczeniu.

In [ ]:
# https://github.com/amaiya/ktrain

In [ ]:
x_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]
x_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

In [8]:
def transformer_model(model_name, x_train, y_train, x_test):
    # https://nbviewer.org/github/amaiya/ktrain/blob/develop/tutorials/tutorial-A3-hugging_face_transformers.ipynb
    t = ktrain.text.Transformer(model_name, maxlen=25, class_names=np.unique(y_train)) # 25 bo pokazuje ze niby 24 jest max
    train = t.preprocess_train(x_train, y_train)
    model = t.get_classifier()
    learner = ktrain.get_learner(model, train_data=train, batch_size=32)
    learner.fit_onecycle(5e-5, 2)
    
    predictor = ktrain.get_predictor(learner.model, preproc=t)
    y_pred = predictor.predict(x_test)
    
    return y_pred

### Customowe

In [ ]:
y_pred = transformer_model('dkleczek/bert-base-polish-cased-v1', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/459 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/30.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/489k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/dkleczek/bert-base-polish-cased-v1/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


Downloading:   0%|          | 0.00/531M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 152s 401ms/step - loss: 0.2611 - accuracy: 0.9147
Epoch 2/2
314/314 [==============================] - 128s 400ms/step - loss: 0.1738 - accuracy: 0.9361
Confusion matrix: 
[[863   3]
 [101  33]]
Classification: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.94       866
           1       0.92      0.25      0.39       134

    accuracy                           0.90      1000
   macro avg       0.91      0.62      0.67      1000
weighted avg       0.90      0.90      0.87      1000

MCC: 
0.4439951499906686


In [ ]:
y_pred = transformer_model('allegro/herbert-large-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/664 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/907k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/556k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/129 [00:00<?, ?B/s]

Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/allegro/herbert-large-cased/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


Downloading:   0%|          | 0.00/1.63G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 414s 1s/step - loss: 0.2904 - accuracy: 0.9141
Epoch 2/2
314/314 [==============================] - 376s 1s/step - loss: 0.2942 - accuracy: 0.9152
Confusion matrix: 
[[866   0]
 [134   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00       134

    accuracy                           0.87      1000
   macro avg       0.43      0.50      0.46      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('Geotrend/distilbert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/557 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/141k [00:00<?, ?B/s]

Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/Geotrend/distilbert-base-pl-cased/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


Downloading:   0%|          | 0.00/243M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 78s 201ms/step - loss: 0.3082 - accuracy: 0.9126
Epoch 2/2
314/314 [==============================] - 66s 201ms/step - loss: 0.2706 - accuracy: 0.9152
Confusion matrix: 
[[866   0]
 [134   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00       134

    accuracy                           0.87      1000
   macro avg       0.43      0.50      0.46      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('Geotrend/bert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/752 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/141k [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/484M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 143s 382ms/step - loss: 0.2954 - accuracy: 0.9144
Epoch 2/2
314/314 [==============================] - 122s 381ms/step - loss: 0.2934 - accuracy: 0.9152
Confusion matrix: 
[[866   0]
 [134   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00       134

    accuracy                           0.87      1000
   macro avg       0.43      0.50      0.46      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Bazowe

In [ ]:
y_pred = transformer_model('xlm-roberta-base', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/512 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/512 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/1.89G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 183s 507ms/step - loss: 0.3198 - accuracy: 0.9121
Epoch 2/2
314/314 [==============================] - 162s 507ms/step - loss: 0.2759 - accuracy: 0.9152
Confusion matrix: 
[[866   0]
 [134   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00       134

    accuracy                           0.87      1000
   macro avg       0.43      0.50      0.46      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('distilbert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/466 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/911M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 93s 255ms/step - loss: 0.3104 - accuracy: 0.9036
Epoch 2/2
314/314 [==============================] - 83s 255ms/step - loss: 0.2377 - accuracy: 0.9179
Confusion matrix: 
[[863   3]
 [120  14]]
Classification: 
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       866
           1       0.82      0.10      0.19       134

    accuracy                           0.88      1000
   macro avg       0.85      0.55      0.56      1000
weighted avg       0.87      0.88      0.83      1000

MCC: 
0.2661884162127535


In [ ]:
y_pred = transformer_model('bert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/1.08G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 159s 435ms/step - loss: 0.2943 - accuracy: 0.9105
Epoch 2/2
314/314 [==============================] - 139s 434ms/step - loss: 0.2455 - accuracy: 0.9171
Confusion matrix: 
[[854  12]
 [118  16]]
Classification: 
              precision    recall  f1-score   support

           0       0.88      0.99      0.93       866
           1       0.57      0.12      0.20       134

    accuracy                           0.87      1000
   macro avg       0.73      0.55      0.56      1000
weighted avg       0.84      0.87      0.83      1000

MCC: 
0.21794237756323684


# Task02

In [ ]:
dataset = load_dataset("poleval2019_cyberbullying", "task02")

Downloading:   0%|          | 0.00/340k [00:00<?, ?B/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

Dataset poleval2019_cyber_bullying downloaded and prepared to /root/.cache/huggingface/datasets/poleval2019_cyber_bullying/task02/1.0.0/ce6060c56dae43c469bab309a7573b86299b0bcc2484e85cfe0ae70b5f770450. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
x_train = dataset["train"]['text']
x_test = dataset["test"]['text']

vectorizer = TfidfVectorizer()
train_vector = vectorizer.fit_transform(x_train).toarray()
test_vector = vectorizer.transform(x_test).toarray()

gnb = GaussianNB()
mnb = MultinomialNB()

y_pred = gnb.fit(train_vector, dataset["train"]["label"]).predict(test_vector)
print("GaussianNB")
get_results(dataset["test"]["label"], y_pred)

y_pred = mnb.fit(train_vector, dataset["train"]["label"]).predict(test_vector) # raczej multinomial jest uzywany do tekstu
print("MultinomialNB")
get_results(dataset["test"]["label"], y_pred)

GaussianNB
Confusion matrix: 
[[763  50  53]
 [ 14   4   7]
 [ 84   5  20]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       866
           1       0.07      0.16      0.10        25
           2       0.25      0.18      0.21       109

    accuracy                           0.79      1000
   macro avg       0.40      0.41      0.40      1000
weighted avg       0.80      0.79      0.79      1000

MCC: 
0.1282543759318036
MultinomialNB
Confusion matrix: 
[[866   0   0]
 [ 25   0   0]
 [109   0   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       109

    accuracy                           0.87      1000
   macro avg       0.29      0.33      0.31      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Przygotowanie pliku pod fasttext
x_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]

with open("train_data2.txt", 'wb') as f:
    f.writelines([f"__label__{label} {sentence}\n".encode() for sentence, label in zip(x_train, y_train)])

In [ ]:
model = fasttext.train_supervised("train_data2.txt")

y_pred, _ = model.predict(x_test)
y_pred = [int(label[0].split("__label__")[1]) for label in y_pred]
y_test = dataset["test"]["label"]
get_results(dataset["test"]["label"], y_pred)

Confusion matrix: 
[[863   2   1]
 [ 22   2   1]
 [102   4   3]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.25      0.08      0.12        25
           2       0.60      0.03      0.05       109

    accuracy                           0.87      1000
   macro avg       0.57      0.37      0.37      1000
weighted avg       0.83      0.87      0.82      1000

MCC: 
0.16001981125515372


In [ ]:
x_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]
x_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

In [ ]:
y_pred = transformer_model('dkleczek/bert-base-polish-cased-v1', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/dkleczek/bert-base-polish-cased-v1/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\




begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 149s 402ms/step - loss: 0.3175 - accuracy: 0.9127
Epoch 2/2
314/314 [==============================] - 128s 400ms/step - loss: 0.2279 - accuracy: 0.9235
Confusion matrix: 
[[854   1  11]
 [ 21   3   1]
 [ 78   8  23]]
Classification: 
              precision    recall  f1-score   support

           0       0.90      0.99      0.94       866
           1       0.25      0.12      0.16        25
           2       0.66      0.21      0.32       109

    accuracy                           0.88      1000
   macro avg       0.60      0.44      0.47      1000
weighted avg       0.85      0.88      0.85      1000

MCC: 
0.3451718122612589


In [ ]:
y_pred = transformer_model('allegro/herbert-large-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/allegro/herbert-large-cased/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\




begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 415s 1s/step - loss: 0.3554 - accuracy: 0.9062
Epoch 2/2
314/314 [==============================] - 375s 1s/step - loss: 0.2926 - accuracy: 0.9150
Confusion matrix: 
[[862   0   4]
 [ 21   0   4]
 [ 90   0  19]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      1.00      0.94       866
           1       0.00      0.00      0.00        25
           2       0.70      0.17      0.28       109

    accuracy                           0.88      1000
   macro avg       0.53      0.39      0.41      1000
weighted avg       0.84      0.88      0.84      1000

MCC: 
0.31722076701322865


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('Geotrend/distilbert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/Geotrend/distilbert-base-pl-cased/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\




begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 77s 201ms/step - loss: 0.3975 - accuracy: 0.9032
Epoch 2/2
314/314 [==============================] - 66s 201ms/step - loss: 0.3147 - accuracy: 0.9152
Confusion matrix: 
[[866   0   0]
 [ 25   0   0]
 [109   0   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       109

    accuracy                           0.87      1000
   macro avg       0.29      0.33      0.31      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('Geotrend/bert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 143s 381ms/step - loss: 0.3624 - accuracy: 0.9127
Epoch 2/2
314/314 [==============================] - 122s 381ms/step - loss: 0.3448 - accuracy: 0.9152
Confusion matrix: 
[[866   0   0]
 [ 25   0   0]
 [109   0   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       109

    accuracy                           0.87      1000
   macro avg       0.29      0.33      0.31      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('xlm-roberta-base', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 182s 507ms/step - loss: 0.3976 - accuracy: 0.9083
Epoch 2/2
314/314 [==============================] - 161s 505ms/step - loss: 0.3121 - accuracy: 0.9149
Confusion matrix: 
[[866   0   0]
 [ 25   0   0]
 [109   0   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       109

    accuracy                           0.87      1000
   macro avg       0.29      0.33      0.31      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('distilbert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 93s 253ms/step - loss: 0.4046 - accuracy: 0.9009
Epoch 2/2
314/314 [==============================] - 83s 255ms/step - loss: 0.3099 - accuracy: 0.9152
Confusion matrix: 
[[866   0   0]
 [ 25   0   0]
 [109   0   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       109

    accuracy                           0.87      1000
   macro avg       0.29      0.33      0.31      1000
weighted avg       0.75      0.87      0.80      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('bert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 12
	95percentile : 21
	99percentile : 24


Is Multi-Label? False


begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
314/314 [==============================] - 159s 434ms/step - loss: 0.3599 - accuracy: 0.9122
Epoch 2/2
314/314 [==============================] - 139s 434ms/step - loss: 0.2940 - accuracy: 0.9157
Confusion matrix: 
[[865   0   1]
 [ 25   0   0]
 [107   0   2]]
Classification: 
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       866
           1       0.00      0.00      0.00        25
           2       0.67      0.02      0.04       109

    accuracy                           0.87      1000
   macro avg       0.51      0.34      0.32      1000
weighted avg       0.82      0.87      0.81      1000

MCC: 
0.08677423467812691


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Dataset jest niezbalansowany

## Task01

In [ ]:
dataset = load_dataset("poleval2019_cyberbullying", "task01")

Downloading:   0%|          | 0.00/2.08k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/340k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/70.1k [00:00<?, ?B/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

Dataset poleval2019_cyber_bullying downloaded and prepared to /root/.cache/huggingface/datasets/poleval2019_cyber_bullying/task01/1.0.0/ce6060c56dae43c469bab309a7573b86299b0bcc2484e85cfe0ae70b5f770450. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:

sampler = RandomOverSampler(sampling_strategy='minority', random_state=13)
x_train_balanced, y_train_balanced = sampler.fit_resample(np.array(dataset["train"]["text"]).reshape((-1, 1)), dataset["train"]["label"])
x_train_balanced = x_train_balanced.reshape((-1))

print(Counter(dataset["train"]["label"]))
print(Counter(y_train_balanced))

Counter({0: 9190, 1: 851})
Counter({0: 9190, 1: 9190})


In [ ]:
x_train = x_train_balanced
x_test = dataset["test"]['text']

vectorizer = TfidfVectorizer()
train_vector = vectorizer.fit_transform(x_train).toarray()
test_vector = vectorizer.transform(x_test).toarray()

gnb = GaussianNB()
mnb = MultinomialNB()

y_pred = gnb.fit(train_vector, y_train_balanced).predict(test_vector)
print("GaussianNB")
get_results(dataset["test"]["label"], y_pred)

y_pred = mnb.fit(train_vector, y_train_balanced).predict(test_vector) # raczej multinomial jest uzywany do tekstu
print("MultinomialNB")
get_results(dataset["test"]["label"], y_pred)

GaussianNB
Confusion matrix: 
[[750 116]
 [101  33]]
Classification: 
              precision    recall  f1-score   support

           0       0.88      0.87      0.87       866
           1       0.22      0.25      0.23       134

    accuracy                           0.78      1000
   macro avg       0.55      0.56      0.55      1000
weighted avg       0.79      0.78      0.79      1000

MCC: 
0.10745050407812812
MultinomialNB
Confusion matrix: 
[[747 119]
 [ 56  78]]
Classification: 
              precision    recall  f1-score   support

           0       0.93      0.86      0.90       866
           1       0.40      0.58      0.47       134

    accuracy                           0.82      1000
   macro avg       0.66      0.72      0.68      1000
weighted avg       0.86      0.82      0.84      1000

MCC: 
0.3808590708020836


In [ ]:
# Przygotowanie pliku pod fasttext
x_train = x_train_balanced
y_train = y_train_balanced

with open("train_data_balanced.txt", 'wb') as f:
    f.writelines([f"__label__{label} {sentence}\n".encode() for sentence, label in zip(x_train, y_train)])

In [ ]:
model = fasttext.train_supervised("train_data_balanced.txt")

y_pred, _ = model.predict(x_test)
y_pred = [int(label[0].split("__label__")[1]) for label in y_pred]
y_test = dataset["test"]["label"]
get_results(dataset["test"]["label"], y_pred)

Confusion matrix: 
[[162 704]
 [  4 130]]
Classification: 
              precision    recall  f1-score   support

           0       0.98      0.19      0.31       866
           1       0.16      0.97      0.27       134

    accuracy                           0.29      1000
   macro avg       0.57      0.58      0.29      1000
weighted avg       0.87      0.29      0.31      1000

MCC: 
0.14393673563899323


In [ ]:
x_train = x_train_balanced
y_train = y_train_balanced
x_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

In [ ]:
y_pred = transformer_model('dkleczek/bert-base-polish-cased-v1', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/dkleczek/bert-base-polish-cased-v1/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\




begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 256s 401ms/step - loss: 0.3224 - accuracy: 0.8518
Epoch 2/2
575/575 [==============================] - 236s 402ms/step - loss: 0.0819 - accuracy: 0.9634
Confusion matrix: 
[[852  14]
 [109  25]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.98      0.93       866
           1       0.64      0.19      0.29       134

    accuracy                           0.88      1000
   macro avg       0.76      0.59      0.61      1000
weighted avg       0.85      0.88      0.85      1000

MCC: 
0.2998397363155773


In [ ]:
y_pred = transformer_model('allegro/herbert-large-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/allegro/herbert-large-cased/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\




begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 730s 1s/step - loss: 0.4423 - accuracy: 0.7589
Epoch 2/2
575/575 [==============================] - 691s 1s/step - loss: 0.6625 - accuracy: 0.5391
Confusion matrix: 
[[  0 866]
 [  0 134]]
Classification: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       866
           1       0.13      1.00      0.24       134

    accuracy                           0.13      1000
   macro avg       0.07      0.50      0.12      1000
weighted avg       0.02      0.13      0.03      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('Geotrend/distilbert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/Geotrend/distilbert-base-pl-cased/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\




begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 130s 201ms/step - loss: 0.4536 - accuracy: 0.7588
Epoch 2/2
575/575 [==============================] - 121s 201ms/step - loss: 0.1467 - accuracy: 0.9280
Confusion matrix: 
[[757 109]
 [ 96  38]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.87      0.88       866
           1       0.26      0.28      0.27       134

    accuracy                           0.80      1000
   macro avg       0.57      0.58      0.58      1000
weighted avg       0.80      0.80      0.80      1000

MCC: 
0.1517239088498655


In [ ]:
y_pred = transformer_model('Geotrend/bert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/752 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/141k [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/484M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 251s 382ms/step - loss: 0.4361 - accuracy: 0.7751
Epoch 2/2
575/575 [==============================] - 225s 381ms/step - loss: 0.1583 - accuracy: 0.9222
Confusion matrix: 
[[751 115]
 [ 94  40]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.87      0.88       866
           1       0.26      0.30      0.28       134

    accuracy                           0.79      1000
   macro avg       0.57      0.58      0.58      1000
weighted avg       0.80      0.79      0.80      1000

MCC: 
0.1559817309614245


In [ ]:
y_pred = transformer_model('xlm-roberta-base', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Is Multi-Label? False


Downloading:   0%|          | 0.00/1.89G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 322s 507ms/step - loss: 0.4840 - accuracy: 0.7486
Epoch 2/2
575/575 [==============================] - 298s 507ms/step - loss: 0.1657 - accuracy: 0.9335
Confusion matrix: 
[[799  67]
 [ 85  49]]
Classification: 
              precision    recall  f1-score   support

           0       0.90      0.92      0.91       866
           1       0.42      0.37      0.39       134

    accuracy                           0.85      1000
   macro avg       0.66      0.64      0.65      1000
weighted avg       0.84      0.85      0.84      1000

MCC: 
0.3066955983963769


In [ ]:
y_pred = transformer_model('distilbert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/466 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/911M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 163s 254ms/step - loss: 0.4276 - accuracy: 0.7823
Epoch 2/2
575/575 [==============================] - 151s 253ms/step - loss: 0.0932 - accuracy: 0.9610
Confusion matrix: 
[[816  50]
 [105  29]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.94      0.91       866
           1       0.37      0.22      0.27       134

    accuracy                           0.84      1000
   macro avg       0.63      0.58      0.59      1000
weighted avg       0.82      0.84      0.83      1000

MCC: 
0.200398023064028


In [ ]:
y_pred = transformer_model('bert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/1.08G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
575/575 [==============================] - 274s 431ms/step - loss: 0.4095 - accuracy: 0.8015
Epoch 2/2
575/575 [==============================] - 254s 431ms/step - loss: 0.1070 - accuracy: 0.9553
Confusion matrix: 
[[818  48]
 [ 94  40]]
Classification: 
              precision    recall  f1-score   support

           0       0.90      0.94      0.92       866
           1       0.45      0.30      0.36       134

    accuracy                           0.86      1000
   macro avg       0.68      0.62      0.64      1000
weighted avg       0.84      0.86      0.85      1000

MCC: 
0.29229554391159424


## Task02

In [9]:
dataset = load_dataset("poleval2019_cyberbullying", "task02")

Downloading:   0%|          | 0.00/2.08k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/340k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/70.1k [00:00<?, ?B/s]

0 examples [00:00, ? examples/s]

0 examples [00:00, ? examples/s]

Dataset poleval2019_cyber_bullying downloaded and prepared to /root/.cache/huggingface/datasets/poleval2019_cyber_bullying/task02/1.0.0/ce6060c56dae43c469bab309a7573b86299b0bcc2484e85cfe0ae70b5f770450. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [10]:
sampler = RandomOverSampler(sampling_strategy='not majority', random_state=13)
x_train_balanced, y_train_balanced = sampler.fit_resample(np.array(dataset["train"]["text"]).reshape((-1, 1)), dataset["train"]["label"])
x_train_balanced = x_train_balanced.reshape((-1))

print(Counter(dataset["train"]["label"]))
print(Counter(y_train_balanced))

Counter({0: 9190, 2: 598, 1: 253})
Counter({0: 9190, 2: 9190, 1: 9190})


In [ ]:
x_train = x_train_balanced
x_test = dataset["test"]['text']

vectorizer = TfidfVectorizer()
train_vector = vectorizer.fit_transform(x_train).toarray()
test_vector = vectorizer.transform(x_test).toarray()

gnb = GaussianNB()
mnb = MultinomialNB()

y_pred = gnb.fit(train_vector, y_train_balanced).predict(test_vector)
print("GaussianNB")
get_results(dataset["test"]["label"], y_pred)

y_pred = mnb.fit(train_vector, y_train_balanced).predict(test_vector) # raczej multinomial jest uzywany do tekstu
print("MultinomialNB")
get_results(dataset["test"]["label"], y_pred)

GaussianNB
Confusion matrix: 
[[767  48  51]
 [ 17   4   4]
 [ 87   5  17]]
Classification: 
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       866
           1       0.07      0.16      0.10        25
           2       0.24      0.16      0.19       109

    accuracy                           0.79      1000
   macro avg       0.40      0.40      0.39      1000
weighted avg       0.79      0.79      0.79      1000

MCC: 
0.1039066729068978
MultinomialNB
Confusion matrix: 
[[710  73  83]
 [  9   9   7]
 [ 47  16  46]]
Classification: 
              precision    recall  f1-score   support

           0       0.93      0.82      0.87       866
           1       0.09      0.36      0.15        25
           2       0.34      0.42      0.38       109

    accuracy                           0.77      1000
   macro avg       0.45      0.53      0.46      1000
weighted avg       0.84      0.77      0.80      1000

MCC: 
0.2789394453912142

In [ ]:
# Przygotowanie pliku pod fasttext
x_train = x_train_balanced
y_train = y_train_balanced

with open("train_data2_balanced.txt", 'wb') as f:
    f.writelines([f"__label__{label} {sentence}\n".encode() for sentence, label in zip(x_train, y_train)])

In [ ]:
model = fasttext.train_supervised("train_data2_balanced.txt")

y_pred, _ = model.predict(x_test)
y_pred = [int(label[0].split("__label__")[1]) for label in y_pred]
y_test = dataset["test"]["label"]
get_results(dataset["test"]["label"], y_pred)

Confusion matrix: 
[[ 41  83 742]
 [  1   1  23]
 [  1   0 108]]
Classification: 
              precision    recall  f1-score   support

           0       0.95      0.05      0.09       866
           1       0.01      0.04      0.02        25
           2       0.12      0.99      0.22       109

    accuracy                           0.15      1000
   macro avg       0.36      0.36      0.11      1000
weighted avg       0.84      0.15      0.10      1000

MCC: 
0.0664843954832379


In [11]:
x_train = x_train_balanced
y_train = y_train_balanced
x_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

In [ ]:
y_pred = transformer_model('dkleczek/bert-base-polish-cased-v1', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/459 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/30.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/489k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Is Multi-Label? False


404 Client Error: Not Found for url: https://huggingface.co/dkleczek/bert-base-polish-cased-v1/resolve/main/tf_model.h5
/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


Downloading:   0%|          | 0.00/531M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 380s 402ms/step - loss: 0.3620 - accuracy: 0.8474
Epoch 2/2
862/862 [==============================] - 355s 402ms/step - loss: 0.0879 - accuracy: 0.9639
Confusion matrix: 
[[822  37   7]
 [ 21   3   1]
 [ 82  11  16]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.95      0.92       866
           1       0.06      0.12      0.08        25
           2       0.67      0.15      0.24       109

    accuracy                           0.84      1000
   macro avg       0.54      0.41      0.41      1000
weighted avg       0.84      0.84      0.82      1000

MCC: 
0.19689417056737404


In [ ]:
y_pred = transformer_model('allegro/herbert-large-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/664 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/907k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/556k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/129 [00:00<?, ?B/s]

404 Client Error: Not Found for url: https://huggingface.co/allegro/herbert-large-cased/resolve/main/tf_model.h5


Is Multi-Label? False


/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


Downloading:   0%|          | 0.00/1.63G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 1074s 1s/step - loss: 0.6110 - accuracy: 0.7085
Epoch 2/2
862/862 [==============================] - 1030s 1s/step - loss: 1.0825 - accuracy: 0.3465
Confusion matrix: 
[[  0 866   0]
 [  0  25   0]
 [  0 109   0]]
Classification: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       866
           1       0.03      1.00      0.05        25
           2       0.00      0.00      0.00       109

    accuracy                           0.03      1000
   macro avg       0.01      0.33      0.02      1000
weighted avg       0.00      0.03      0.00      1000

MCC: 
0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_pred = transformer_model('Geotrend/distilbert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/557 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/141k [00:00<?, ?B/s]

404 Client Error: Not Found for url: https://huggingface.co/Geotrend/distilbert-base-pl-cased/resolve/main/tf_model.h5


Is Multi-Label? False


/usr/local/lib/python3.7/dist-packages/ktrain/text/preprocessor.py:1067: UserWarning: Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. You will need PyTorch installed for this.
  warnings.warn('Could not find Tensorflow version of model.  Attempting to download/load PyTorch version as TensorFlow model using from_pt=True. ' +\


Downloading:   0%|          | 0.00/243M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 196s 201ms/step - loss: 0.5583 - accuracy: 0.7312
Epoch 2/2
862/862 [==============================] - 182s 201ms/step - loss: 0.1963 - accuracy: 0.9024
Confusion matrix: 
[[753  99  14]
 [ 21   4   0]
 [ 73  24  12]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.87      0.88       866
           1       0.03      0.16      0.05        25
           2       0.46      0.11      0.18       109

    accuracy                           0.77      1000
   macro avg       0.46      0.38      0.37      1000
weighted avg       0.82      0.77      0.78      1000

MCC: 
0.11736198520888155


In [ ]:
y_pred = transformer_model('Geotrend/bert-base-pl-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Is Multi-Label? False


begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 360s 382ms/step - loss: 0.5386 - accuracy: 0.7472
Epoch 2/2
862/862 [==============================] - 337s 382ms/step - loss: 0.2069 - accuracy: 0.8959
Confusion matrix: 
[[761  96   9]
 [ 20   5   0]
 [ 76  24   9]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       866
           1       0.04      0.20      0.07        25
           2       0.50      0.08      0.14       109

    accuracy                           0.78      1000
   macro avg       0.48      0.39      0.36      1000
weighted avg       0.82      0.78      0.78      1000

MCC: 
0.11396934680718569


In [ ]:
y_pred = transformer_model('xlm-roberta-base', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/512 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/512 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/1.89G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 8910s 10s/step - loss: 0.5557 - accuracy: 0.7517
Epoch 2/2
862/862 [==============================] - 8966s 10s/step - loss: 0.1422 - accuracy: 0.9460
Confusion matrix: 
[[797  47  22]
 [ 19   4   2]
 [ 72  13  24]]
Classification: 
              precision    recall  f1-score   support

           0       0.90      0.92      0.91       866
           1       0.06      0.16      0.09        25
           2       0.50      0.22      0.31       109

    accuracy                           0.82      1000
   macro avg       0.49      0.43      0.43      1000
weighted avg       0.83      0.82      0.82      1000

MCC: 
0.22274557527293304


In [ ]:
y_pred = transformer_model('distilbert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/466 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/911M [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 4395s 5s/step - loss: 0.5020 - accuracy: 0.7716
Epoch 2/2
862/862 [==============================] - 4325s 5s/step - loss: 0.0882 - accuracy: 0.9639
Confusion matrix: 
[[814  40  12]
 [ 22   1   2]
 [ 82  10  17]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.94      0.91       866
           1       0.02      0.04      0.03        25
           2       0.55      0.16      0.24       109

    accuracy                           0.83      1000
   macro avg       0.48      0.38      0.39      1000
weighted avg       0.83      0.83      0.82      1000

MCC: 
0.16933955371328283


In [12]:
y_pred = transformer_model('bert-base-multilingual-cased', x_train, y_train, x_test)
get_results(dataset["test"]["label"], y_pred)

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

preprocessing train...
language: pl
train sequence lengths:
	mean : 13
	95percentile : 20
	99percentile : 23


Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Is Multi-Label? False


Downloading:   0%|          | 0.00/1.08G [00:00<?, ?B/s]



begin training using onecycle policy with max lr of 5e-05...
Epoch 1/2
862/862 [==============================] - 407s 434ms/step - loss: 0.4740 - accuracy: 0.7915
Epoch 2/2
862/862 [==============================] - 382s 434ms/step - loss: 0.1025 - accuracy: 0.9596
Confusion matrix: 
[[816  37  13]
 [ 19   2   4]
 [ 86  10  13]]
Classification: 
              precision    recall  f1-score   support

           0       0.89      0.94      0.91       866
           1       0.04      0.08      0.05        25
           2       0.43      0.12      0.19       109

    accuracy                           0.83      1000
   macro avg       0.45      0.38      0.38      1000
weighted avg       0.82      0.83      0.81      1000

MCC: 
0.15399794331268118
